server:
 port: 8080
spring:
 redis:
  database: 0
  host: 192.168.0.24
  password: ''
  jedis:
   pool:
    max-active: 200
    max-idle: 1
    max-wait: -1
    min-idle: 0
  port: 6379
  timeout: 1000